<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="lexiconmodel" nsURI="lexicon" nsPrefix="home.computerlinguistik">
  <eClassifiers xsi:type="ecore:EClass" name="Lexicon">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eintraege" upperBound="-1"
        eType="#//Eintrag" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lg" eType="#//GrammatikalischeKategorie"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Eintrag">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wort" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Wortart"/>
  <eClassifiers xsi:type="ecore:EClass" name="Auspraegung">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="grammatikalischeKategorie"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Person">
    <eLiterals name="EEnumLiteral3" value="3"/>
    <eLiterals name="EEnumLiteral4" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Numerus"/>
  <eClassifiers xsi:type="ecore:EClass" name="GrammatikalischeKategorie">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bezeichnung"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="l1" eType="#//Lexicon"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Subkategorisierung">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bezeichnung"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gramatikalischeKategorien"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuspraegungenContainer"/>
  <eClassifiers xsi:type="ecore:EClass" name="Auspraegungen"/>
</ecore:EPackage>
